// <auto-generated />
using System;
using Cosmetic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Cosmetic.Migrations
{
    [DbContext(typeof(MyPhamContext))]
    partial class MyPhamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Cosmetic.Models.BanBe", b =>
                {
                    b.Property<int>("MaBb")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaBB");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(10);

                    b.Property<string>("HoTen")
                        .HasMaxLength(50);

                    b.Property<string>("MaKh")
                        .HasColumnName("MaKH")
                        .HasMaxLength(50);

                    b.Property<int?>("MaSp")
                        .HasColumnName("MaSP");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("timestamp");

                    b.HasKey("MaBb");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaSp");

                    b.ToTable("BanBe");
                });

            modelBuilder.Entity("Cosmetic.Models.BinhLuan", b =>
                {
                    b.Property<int>("MaBl")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaBL");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("HoTen")
                        .HasMaxLength(50);

                    b.Property<string>("MaKh")
                        .HasColumnName("MaKH")
                        .HasMaxLength(50);

                    b.Property<int?>("MaSp")
                        .HasColumnName("MaSP");

                    b.Property<DateTime>("NgayBl")
                        .HasColumnName("NgayBL")
                        .HasColumnType("timestamp");

                    b.Property<string>("NoiDung");

                    b.HasKey("MaBl");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaSp");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("Cosmetic.Models.Blog", b =>
                {
                    b.Property<int>("MaBlog")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MaLoaiBlog");

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("timestamp");

                    b.Property<string>("NoiDung");

                    b.Property<string>("TenBlog")
                        .HasMaxLength(50);

                    b.HasKey("MaBlog");

                    b.HasIndex("MaLoaiBlog");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("Cosmetic.Models.ChiTietHd", b =>
                {
                    b.Property<int>("MaCt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaCT");

                    b.Property<double?>("DonGia");

                    b.Property<double?>("GiamGia");

                    b.Property<int?>("MaHd")
                        .HasColumnName("MaHD");

                    b.Property<int?>("MaSp")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuong");

                    b.HasKey("MaCt");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietHD");
                });

            modelBuilder.Entity("Cosmetic.Models.ChuDe", b =>
                {
                    b.Property<int>("MaCd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaCD");

                    b.Property<string>("MaNv")
                        .HasColumnName("MaNV")
                        .HasMaxLength(50);

                    b.Property<string>("TenCd")
                        .HasColumnName("TenCD")
                        .HasMaxLength(50);

                    b.HasKey("MaCd");

                    b.HasIndex("MaNv");

                    b.ToTable("ChuDe");
                });

            modelBuilder.Entity("Cosmetic.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaHD");

                    b.Property<string>("CachThanhToan")
                        .HasMaxLength(50);

                    b.Property<string>("CachVanChuyen")
                        .HasMaxLength(50);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DiaChiNgNhan")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50);

                    b.Property<string>("DtngNhan")
                        .HasColumnName("DTNgNhan")
                        .HasMaxLength(50);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(50);

                    b.Property<string>("HoTen")
                        .HasMaxLength(50);

                    b.Property<string>("MaKh")
                        .HasColumnName("MaKH")
                        .HasMaxLength(50);

                    b.Property<string>("MaNv")
                        .HasColumnName("MaNV")
                        .HasMaxLength(50);

                    b.Property<int?>("MaTrangThai");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("timestamp");

                    b.Property<double?>("PhiVanChuyen");

                    b.Property<string>("TenNgNhan")
                        .HasMaxLength(50);

                    b.HasKey("MaHd");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Cosmetic.Models.HoiDap", b =>
                {
                    b.Property<int>("MaHdap")
                        .HasColumnName("MaHDap");

                    b.Property<string>("CauHoi")
                        .HasMaxLength(50);

                    b.Property<string>("MaNv")
                        .HasColumnName("MaNV")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayDua")
                        .HasColumnType("timestamp");

                    b.Property<string>("TraLoi")
                        .HasMaxLength(50);

                    b.HasKey("MaHdap");

                    b.HasIndex("MaNv");

                    b.ToTable("HoiDap");
                });

            modelBuilder.Entity("Cosmetic.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasColumnName("MaKH")
                        .HasMaxLength(50);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<bool?>("GioiTinh");

                    b.Property<bool?>("HieuLuc");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("RandomKey")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("VaiTro");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Cosmetic.Models.KhoHang", b =>
                {
                    b.Property<int>("MaKho")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MaSp")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuong");

                    b.HasKey("MaKho");

                    b.HasIndex("MaSp");

                    b.ToTable("KhoHang");
                });

            modelBuilder.Entity("Cosmetic.Models.LienHe", b =>
                {
                    b.Property<int>("MaGy")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaGY");

                    b.Property<string>("DienThoai")
                        .HasColumnName("DIenThoai")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("HoTen")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayGy")
                        .HasColumnName("NgayGY")
                        .HasColumnType("timestamp");

                    b.Property<string>("NoiDung");

                    b.Property<string>("TieuDe");

                    b.HasKey("MaGy");

                    b.ToTable("LienHe");
                });

            modelBuilder.Entity("Cosmetic.Models.Loai", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MoTa")
                        .HasMaxLength(50);

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50);

                    b.Property<string>("TenLoaiAlias")
                        .HasMaxLength(50);

                    b.HasKey("MaLoai");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("Cosmetic.Models.LoaiBlog", b =>
                {
                    b.Property<int>("MaLoaiBlog")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MoTa")
                        .HasMaxLength(50);

                    b.Property<string>("TenLoaiBlog");

                    b.HasKey("MaLoaiBlog");

                    b.ToTable("LoaiBlog");
                });

            modelBuilder.Entity("Cosmetic.Models.NhaCungCap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasColumnName("MaNCC")
                        .HasMaxLength(50);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50);

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Logo")
                        .HasMaxLength(50);

                    b.Property<string>("MoTa");

                    b.Property<string>("TenCongTy")
                        .HasMaxLength(50);

                    b.HasKey("MaNcc");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("Cosmetic.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasColumnName("MaNV")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("HoTen")
                        .HasMaxLength(50);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50);

                    b.HasKey("MaNv");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Cosmetic.Models.PhanCong", b =>
                {
                    b.Property<int>("MaPc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaPC");

                    b.Property<bool?>("HieuLuc");

                    b.Property<string>("MaNv")
                        .HasColumnName("MaNV")
                        .HasMaxLength(50);

                    b.Property<string>("MaPb")
                        .HasColumnName("MaPB")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<DateTime?>("NgayPc")
                        .HasColumnName("NgayPC")
                        .HasColumnType("timestamp");

                    b.HasKey("MaPc");

                    b.HasIndex("MaNv");

                    b.HasIndex("MaPb");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("Cosmetic.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaPq")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaPQ");

                    b.Property<string>("MaPb")
                        .HasColumnName("MaPB")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<int?>("MaTrang");

                    b.Property<bool?>("Sua");

                    b.Property<bool?>("Them");

                    b.Property<bool?>("Xem");

                    b.Property<bool?>("Xoa");

                    b.HasKey("MaPq");

                    b.HasIndex("MaPb");

                    b.HasIndex("MaTrang");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("Cosmetic.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPb")
                        .HasColumnName("MaPB")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("TenPb")
                        .HasColumnName("TenPB")
                        .HasMaxLength(50);

                    b.Property<string>("ThongTin");

                    b.HasKey("MaPb");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("Cosmetic.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaSP");

                    b.Property<double?>("DonGia");

                    b.Property<double?>("GiaCu");

                    b.Property<string>("Hinh")
                        .HasMaxLength(50);

                    b.Property<string>("Hinh2")
                        .HasMaxLength(50);

                    b.Property<int?>("MaHieu");

                    b.Property<int?>("MaLoai");

                    b.Property<string>("MaNcc")
                        .HasColumnName("MaNCC")
                        .HasMaxLength(50);

                    b.Property<string>("MoTa");

                    b.Property<bool?>("SpHot");

                    b.Property<string>("TenAlias")
                        .HasMaxLength(50);

                    b.Property<string>("TenSp")
                        .HasColumnName("TenSP")
                        .HasMaxLength(50);

                    b.HasKey("MaSp");

                    b.HasIndex("MaHieu");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNcc");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("Cosmetic.Models.ThuongHieu", b =>
                {
                    b.Property<int>("MaHieu")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hinh")
                        .HasMaxLength(50);

                    b.Property<string>("TenHieu")
                        .HasMaxLength(50);

                    b.HasKey("MaHieu");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("Cosmetic.Models.TrangThai", b =>
                {
                    b.Property<int>("MaTrangThai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50);

                    b.Property<string>("TenTrangThai")
                        .HasMaxLength(50);

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("Cosmetic.Models.TrangWeb", b =>
                {
                    b.Property<int>("MaTrang")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenTrang")
                        .HasMaxLength(50);

                    b.Property<string>("Url")
                        .HasColumnName("URL")
                        .HasMaxLength(250);

                    b.HasKey("MaTrang");

                    b.ToTable("TrangWeb");
                });

            modelBuilder.Entity("Cosmetic.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaYT");

                    b.Property<string>("MaKh")
                        .HasColumnName("MaKH")
                        .HasMaxLength(50);

                    b.Property<int?>("MaSp")
                        .HasColumnName("MaSP");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NgayChon")
                        .HasColumnType("timestamp");

                    b.HasKey("MaYt");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaSp");

                    b.ToTable("YeuThich");
                });

            modelBuilder.Entity("Cosmetic.Models.BanBe", b =>
                {
                    b.HasOne("Cosmetic.Models.KhachHang", "MaKhNavigation")
                        .WithMany("BanBe")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_BanBe_KhachHang");

                    b.HasOne("Cosmetic.Models.SanPham", "MaSpNavigation")
                        .WithMany("BanBe")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_BanBe_SanPham");
                });

            modelBuilder.Entity("Cosmetic.Models.BinhLuan", b =>
                {
                    b.HasOne("Cosmetic.Models.KhachHang", "MaKhNavigation")
                        .WithMany("BinhLuan")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_BinhLuan_KhachHang");

                    b.HasOne("Cosmetic.Models.SanPham", "MaSpNavigation")
                        .WithMany("BinhLuan")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_BinhLuan_SanPham");
                });

            modelBuilder.Entity("Cosmetic.Models.Blog", b =>
                {
                    b.HasOne("Cosmetic.Models.LoaiBlog", "MaLoaiBlogNavigation")
                        .WithMany("Blog")
                        .HasForeignKey("MaLoaiBlog")
                        .HasConstraintName("FK_Blog_LoaiBlog");
                });

            modelBuilder.Entity("Cosmetic.Models.ChiTietHd", b =>
                {
                    b.HasOne("Cosmetic.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietHd")
                        .HasForeignKey("MaHd")
                        .HasConstraintName("FK_ChiTietHD_HoaDon");

                    b.HasOne("Cosmetic.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietHd")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_ChiTietHD_SanPham");
                });

            modelBuilder.Entity("Cosmetic.Models.ChuDe", b =>
                {
                    b.HasOne("Cosmetic.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ChuDe")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK_ChuDe_NhanVien");
                });

            modelBuilder.Entity("Cosmetic.Models.HoaDon", b =>
                {
                    b.HasOne("Cosmetic.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_HoaDon_KhachHang");

                    b.HasOne("Cosmetic.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK_HoaDon_NhanVien");

                    b.HasOne("Cosmetic.Models.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK_HoaDon_TrangThai");
                });

            modelBuilder.Entity("Cosmetic.Models.HoiDap", b =>
                {
                    b.HasOne("Cosmetic.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoiDap")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK_HoiDap_NhanVien");
                });

            modelBuilder.Entity("Cosmetic.Models.KhoHang", b =>
                {
                    b.HasOne("Cosmetic.Models.SanPham", "MaSpNavigation")
                        .WithMany("KhoHang")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_KhoHang_SanPham");
                });

            modelBuilder.Entity("Cosmetic.Models.PhanCong", b =>
                {
                    b.HasOne("Cosmetic.Models.NhanVien", "MaNvNavigation")
                        .WithMany("PhanCong")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK_PhanCong_NhanVien");

                    b.HasOne("Cosmetic.Models.PhongBan", "MaPbNavigation")
                        .WithMany("PhanCong")
                        .HasForeignKey("MaPb")
                        .HasConstraintName("FK_PhanCong_PhongBan");
                });

            modelBuilder.Entity("Cosmetic.Models.PhanQuyen", b =>
                {
                    b.HasOne("Cosmetic.Models.PhongBan", "MaPbNavigation")
                        .WithMany("PhanQuyen")
                        .HasForeignKey("MaPb")
                        .HasConstraintName("FK_PhanQuyen_PhongBan");

                    b.HasOne("Cosmetic.Models.TrangWeb", "MaTrangNavigation")
                        .WithMany("PhanQuyen")
                        .HasForeignKey("MaTrang")
                        .HasConstraintName("FK_PhanQuyen_TrangWeb");
                });

            modelBuilder.Entity("Cosmetic.Models.SanPham", b =>
                {
                    b.HasOne("Cosmetic.Models.ThuongHieu", "MaHieuNavigation")
                        .WithMany("SanPham")
                        .HasForeignKey("MaHieu")
                        .HasConstraintName("FK_SanPham_ThuongHieu");

                    b.HasOne("Cosmetic.Models.Loai", "MaLoaiNavigation")
                        .WithMany("SanPham")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK_SanPham_Loai");

                    b.HasOne("Cosmetic.Models.NhaCungCap", "MaNccNavigation")
                        .WithMany("SanPham")
                        .HasForeignKey("MaNcc")
                        .HasConstraintName("FK_SanPham_NhaCungCap");
                });

            modelBuilder.Entity("Cosmetic.Models.ThuongHieu", b =>
                {
                    b.HasOne("Cosmetic.Models.ThuongHieu", "MaHieuNavigation")
                        .WithOne("InverseMaHieuNavigation")
                        .HasForeignKey("Cosmetic.Models.ThuongHieu", "MaHieu")
                        .HasConstraintName("FK_ThuongHieu_ThuongHieu");
                });

            modelBuilder.Entity("Cosmetic.Models.YeuThich", b =>
                {
                    b.HasOne("Cosmetic.Models.KhachHang", "MaKhNavigation")
                        .WithMany("YeuThich")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_YeuThich_KhachHang");

                    b.HasOne("Cosmetic.Models.SanPham", "MaSpNavigation")
                        .WithMany("YeuThich")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK_YeuThich_SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
